use Consultas

select CLIENTES.[CÓDIGO CLIENTE],CLIENTES.POBLACIÓN,CLIENTES.DIRECCIÓN,pedidos.[NÚMERO DE PEDIDO],PEDIDOS.[CÓDIGO CLIENTE],PEDIDOS.[FORMA DE PAGO] from CLIENTES left join PEDIDOS on CLIENTES.[CÓDIGO CLIENTE] =PEDIDOS.[CÓDIGO CLIENTE]

where CLIENTES.POBLACIÓN='MADRID' and PEDIDOS.[NÚMERO DE PEDIDO] is null