DROP TABLE DATOS ;
DROP TABLE ALUMNO;
CREATE TABLE CARRERA (
ID_CARRERA INT PRIMARY KEY NOT NULL,
CARRERA VARCHAR2(20) NOT NULL
);
CREATE TABLE ALUMNO(
ID_ALUMNO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(20)NOT NULL,
APELLIDOS VARCHAR2(20)NOT NULL,
ID_CARRERA INT NOT NULL,
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
);

CREATE table datos (
ID_DATOS INT  PRIMARY KEY NOT NULL,
ID_ALUMNO INT NOT NULL,
EMAIL VARCHAR2(20)NOT NULL,
EDAD NUMBER(3)NOT NULL,
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO)
);

INSERT INTO CARRERA VALUES(1,'ING.SISTEMAS');
INSERT INTO CARRERA VALUES(2,'LIC.DERECHO');
INSERT INTO CARRERA VALUES(3,'LIC.ADMINISTRACION');

INSERT INTO ALUMNO VALUES(1,'DAVID','HERNANDEZ PEREZ',1);
INSERT INTO ALUMNO VALUES(2,'MARIANA','MARTINEZ LUNA',2);
INSERT INTO ALUMNO VALUES(3,'TATIANA','RAMIREZ RAMIREZ',1);
INSERT INTO ALUMNO VALUES(4,'JUAN','ARCILA CAMPAZ',3);

INSERT INTO DATOS VALUES(1,1,'HACKRO@YAHOO.COM',22);
INSERT INTO DATOS VALUES(2,2,'MARIANA',14);
INSERT INTO DATOS VALUES(3,3,'TATIANA',21);
INSERT INTO DATOS VALUES(4,4,'JUANDAVIDARCILA18@',21);